# Generated by Django 5.1 on 2024-08-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ttareungilocation',
            table='ttareungi_location',
        ),
    ]
