# Generated by Django 5.1 on 2024-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilities_location',
            fields=[
                ('facil_lo_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contents_name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'facilities_location',
            },
        ),
    ]
