# Generated by Django 5.1 on 2024-08-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.IntegerField()),
                ('column3', models.DateField()),
            ],
        ),
    ]
